#!/usr/bin/env bash
# update-guides.sh - Sync AI development guides between projects
# Version: 1.0.0
# Description: Synchronizes 7 AI guides from framework to target projects

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
FRAMEWORK_DIR=""
TARGET_DIR=""

# Usage information
usage() {
    cat << EOF
Usage: update-guides.sh [--from FRAMEWORK_DIR] [TARGET_PROJECT]

Sync AI development guides (7 guides) from framework to target project.

Arguments:
    --from FRAMEWORK_DIR    Path to framework directory (required)
    TARGET_PROJECT          Path to target project (default: current directory)

Examples:
    update-guides.sh --from ~/dev/ai-dev ../u-safe
    update-guides.sh --from ~/dev/ai-dev .
    update-guides.sh --from /path/to/ai-dev /path/to/target

AI Guides synced (20 files across 4 subdirectories):
    - workflow/ (6 files): ADR_GUIDE.md, CLAUDE_MD_GUIDE.md, ISSUE_LIFECYCLE_GUIDE.md, PROJECT_PLANNING_GUIDE.md, SKILL_GUIDE.md, README.md
    - doc-templates/ (3 files): MANAGE_DOCS_GUIDE.md, STACK_TAGS.md, README.md
    - rules/ (5 files): RULES_GUIDE.md, RULES_MAPPING.md, PROFILE_CONSISTENCY.md, MIGRATION_REPORT.md, README.md
    - profiles/ (4 files): tauri.md, nextjs-aws.md, tauri-aws.md, README.md
    - Root files (2): README.md, HARDCODING_POLICY.md
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --from)
            FRAMEWORK_DIR="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            TARGET_DIR="$1"
            shift
            ;;
    esac
done

# Validate framework directory
if [[ -z "$FRAMEWORK_DIR" ]]; then
    echo -e "${RED}❌ 错误：必须指定框架目录 (--from)${NC}"
    echo ""
    usage
    exit 1
fi

# Set default target directory if not specified
if [[ -z "$TARGET_DIR" ]]; then
    TARGET_DIR="."
fi

# Validate and resolve absolute paths
if [[ ! -d "$FRAMEWORK_DIR" ]]; then
    echo -e "${RED}❌ 错误：框架目录不存在${NC}"
    echo "   指定路径: $FRAMEWORK_DIR"
    exit 1
fi

if [[ ! -d "$TARGET_DIR" ]]; then
    echo -e "${RED}❌ 错误：目标目录不存在${NC}"
    echo "   指定路径: $TARGET_DIR"
    exit 1
fi

FRAMEWORK_DIR="$(cd "$FRAMEWORK_DIR" && pwd)"
TARGET_DIR="$(cd "$TARGET_DIR" && pwd)"

# Check if framework source directory exists
FRAMEWORK_GUIDES="$FRAMEWORK_DIR/.claude/guides"
if [[ ! -d "$FRAMEWORK_GUIDES" ]]; then
    echo -e "${RED}❌ 错误：框架目录不存在 AI guides${NC}"
    echo "   期望路径: $FRAMEWORK_GUIDES"
    echo ""
    echo "请确保框架目录包含 .claude/guides/ 并且包含 4 个子目录（workflow, doc-templates, rules, profiles）。"
    exit 1
fi

# Check if target directory is writable
TARGET_GUIDES="$TARGET_DIR/.claude/guides"
if [[ ! -w "$TARGET_DIR" ]]; then
    echo -e "${RED}❌ 错误：目标目录无写入权限${NC}"
    echo "   目标路径: $TARGET_DIR"
    exit 1
fi

echo -e "${BLUE}📋 同步 AI 开发指南${NC}"
echo "   框架: $FRAMEWORK_GUIDES"
echo "   目标: $TARGET_GUIDES"
echo ""

# Count source guides
GUIDE_COUNT=$(find "$FRAMEWORK_GUIDES" -name "*.md" -type f | wc -l | tr -d ' ')
if [[ $GUIDE_COUNT -lt 20 ]]; then
    echo -e "${YELLOW}⚠️  警告：框架中仅找到 $GUIDE_COUNT 个 guide 文件（期望 20 个）${NC}"
fi

# Delete existing target directory if present
if [[ -d "$TARGET_GUIDES" ]]; then
    echo -e "${YELLOW}🗑️  删除现有 ai-guides 目录...${NC}"
    rm -rf "$TARGET_GUIDES"
fi

# Create target docs directory if it doesn't exist
mkdir -p "$TARGET_DIR/docs"

# Copy AI guides from framework to target
echo -e "${BLUE}📋 拷贝 AI 开发指南...${NC}"
cp -r "$FRAMEWORK_GUIDES" "$TARGET_GUIDES"

# Verify copy succeeded
if [[ ! -d "$TARGET_GUIDES" ]]; then
    echo -e "${RED}❌ 错误：拷贝失败${NC}"
    exit 1
fi

# Create version marker file
echo -e "${BLUE}📝 创建版本标记...${NC}"
VERSION_FILE="$TARGET_GUIDES/.ai-guides-version"
cat > "$VERSION_FILE" << EOF
# AI Guides Version Tracking
# Auto-generated by update-guides.sh

framework_path: $FRAMEWORK_DIR
framework_commit: $(cd "$FRAMEWORK_DIR" && git rev-parse HEAD 2>/dev/null || echo "unknown")
synced_at: $(date -Iseconds)
synced_by: update-guides.sh v1.0.0
guide_count: $(find "$TARGET_GUIDES" -name "*.md" -type f | wc -l | tr -d ' ')
EOF

# Generate sync report
echo ""
echo -e "${GREEN}✅ 同步完成${NC}"
echo ""
echo "| Guide | 状态 | 用途 |"
echo "|-------|------|------|"

# Check each expected guide
GUIDES=(
    "ADR_GUIDE.md:AI 创建 ADR 的参考标准"
    "CLAUDE_MD_GUIDE.md:AI 维护 CLAUDE.md 的参考标准"
    "ISSUE_LIFECYCLE_GUIDE.md:AI 执行 issue 工作流的参考标准"
    "DOCS_GUIDE.md:AI 组织文档的参考标准"
    "PROJECT_PLANNING_GUIDE.md:AI 规划项目的参考标准"
    "SKILL_GUIDE.md:AI 创建技能的参考标准"
)

for guide_info in "${GUIDES[@]}"; do
    guide_name="${guide_info%%:*}"
    guide_desc="${guide_info##*:}"

    if [[ -f "$TARGET_GUIDES/$guide_name" ]]; then
        echo "| $guide_name | ✅ | $guide_desc |"
    else
        echo "| $guide_name | ❌ | $guide_desc |"
    fi
done

echo ""
echo -e "${GREEN}AI 现在可以使用最新的开发参考标准${NC}"
echo ""
echo "版本文件: $VERSION_FILE"
